import React from 'react';

export interface GithubStatsProps {
  username?: string;
  name?: string;
  stars?: number;
  followers?: number;
  repos?: number; // Renamed from forks
  avatarUrl?: string;
  theme?: 'dark' | 'light';
}

export const GithubStats: React.FC<GithubStatsProps> = ({
  username = "octocat",
  name = "The Octocat",
  stars = 0, // Reset default to 0 to avoid fake data
  followers = 500,
  repos = 30, // Renamed default
  avatarUrl = "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
  theme = 'dark'
}) => {
  const isDark = theme === 'dark';
  const bgColor = isDark ? '#0d1117' : '#ffffff';
  const textColor = isDark ? '#c9d1d9' : '#24292f';
  const borderColor = isDark ? '#30363d' : '#e1e4e8';
  const secondaryText = isDark ? '#8b949e' : '#586069';

  return (
    <div
      style={{
        display: 'flex',
        height: '100%',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent', 
        fontFamily: 'Instrument Sans',
      }}
    >
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          width: '480px',
          padding: '20px',
          backgroundColor: bgColor,
          border: `1px solid ${borderColor}`,
          borderRadius: '12px',
          boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
          color: textColor,
        }}
      >
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', marginBottom: '16px' }}>
          <img
            src={avatarUrl}
            alt="Avatar"
            width={64}
            height={64}
            style={{
              borderRadius: '50%',
              marginRight: '16px',
              border: `2px solid ${borderColor}`
            }}
          />
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            <span style={{ fontSize: '20px', fontWeight: 700 }}>{name}</span>
            <span style={{ fontSize: '14px', color: secondaryText }}>@{username}</span>
          </div>
        </div>

        {/* Stats Grid */}
        <div style={{ display: 'flex', flexDirection: 'row', gap: '12px', marginTop: '8px' }}>
             {/* Stars (Placeholder/Real) */}
             <div style={{ display: 'flex', flex: 1,  flexDirection: 'column', alignItems: 'center', padding: '10px', backgroundColor: isDark ? '#161b22' : '#f6f8fa', borderRadius: '8px', border: `1px solid ${borderColor}` }}>
                <span style={{ fontSize: '18px', fontWeight: 700 }}>{stars}</span>
                <span style={{ fontSize: '12px', color: secondaryText }}>Stars</span>
             </div>
             {/* Followers */}
             <div style={{ display: 'flex',  flex: 1, flexDirection: 'column', alignItems: 'center', padding: '10px', backgroundColor: isDark ? '#161b22' : '#f6f8fa', borderRadius: '8px', border: `1px solid ${borderColor}` }}>
                <span style={{ fontSize: '18px', fontWeight: 700 }}>{followers}</span>
                <span style={{ fontSize: '12px', color: secondaryText }}>Followers</span>
             </div>
              {/* Repos */}
             <div style={{ display: 'flex',  flex: 1, flexDirection: 'column', alignItems: 'center', padding: '10px', backgroundColor: isDark ? '#161b22' : '#f6f8fa', borderRadius: '8px', border: `1px solid ${borderColor}` }}>
                <span style={{ fontSize: '18px', fontWeight: 700 }}>{repos}</span>
                <span style={{ fontSize: '12px', color: secondaryText }}>Repos</span>
             </div>
        </div>
        
        {/* Footer / Graph Mock */}
        <div style={{ display: 'flex', marginTop: '16px', fontSize: '10px', color: secondaryText, justifyContent: 'flex-end' }}>
            Generated by Readme-UI
        </div>
      </div>
    </div>
  );
};
